<a href="https://colab.research.google.com/github/Subhadeep-Paul/RDKit_World/blob/main/Fundamentals/Pandas_Cheminformatics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Quick Intro to Pandas for Cheminformatics.
This notebook provides an overview of the Pandas library for data handling and manipulation in Python scripts.

In [45]:
%%capture
import sys
if 'google.colab' in sys.modules:
  !pip install pandas numpy seaborn

Necessary Python libraries are imported.

In [46]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

This magic command enables to render matplotlib plots directly
within the notebook output rather than opening in a seperate window.

In [47]:
%matplotlib inline

In [48]:
df = pd.read_csv("https://raw.githubusercontent.com/Subhadeep-Paul/RDKit_World/refs/heads/main/data/ChEMBL_hERG.csv")

##Getting an overview of the data.
Let's look at datatype for each of the columns.

In [49]:
df.dtypes

canonical_smiles      object
molregno               int64
mol_chembl_id         object
standard_relation     object
standard_value       float64
standard_type         object
standard_units        object
description           object
organism              object
assay_type            object
confidence_score       int64
pref_name             object
tgt_chembl_id         object
dtype: object

Examine the number of rows and columns in the dataframe.

In [50]:
df.shape

(8989, 13)

We can also use the `columns` feature to look at the column names.

In [51]:
df.columns

Index(['canonical_smiles', 'molregno', 'mol_chembl_id', 'standard_relation',
       'standard_value', 'standard_type', 'standard_units', 'description',
       'organism', 'assay_type', 'confidence_score', 'pref_name',
       'tgt_chembl_id'],
      dtype='object')

Let's have a glance of the dataframe using `head()` method. simply writing the DataFrame name also works. Here, simply replace "df.head()" with "df" & look what is the difference. Try it!

In [52]:
df.head()

,canonical_smiles,molregno,mol_chembl_id,standard_relation,standard_value,standard_type,standard_units,description,organism,assay_type,confidence_score,pref_name,tgt_chembl_id
0,COCC(=O)O[C@]1(CCN(C)CCCc2nc3ccccc3[nH]2)CCc4c...,72035,CHEMBL45816,=,1430.0,IC50,nM,K+ channel blocking activity in COS-7 African ...,Homo sapiens,F,9,HERG,CHEMBL240
1,CC(C)COCC(CN(Cc1ccccc1)c2ccccc2)N3CCCC3,112651,CHEMBL1008,=,550.0,IC50,nM,K+ channel blocking activity in COS-7 African ...,Homo sapiens,F,9,HERG,CHEMBL240
2,COc1c(N2C[C@@H]3CCCN[C@@H]3C2)c(F)cc4C(=O)C(=C...,1788,CHEMBL32,=,129000.0,IC50,nM,K+ channel blocking activity in Chinese hamste...,Homo sapiens,F,9,HERG,CHEMBL240
3,COc1c(N2CCNC(C)C2)c(F)cc3C(=O)C(=CN(C4CC4)c13)...,1712,CHEMBL31,=,130000.0,IC50,nM,K+ channel blocking activity in Chinese hamste...,Homo sapiens,F,9,HERG,CHEMBL240
4,CC1CN(CCN1)c2cc3N(C=C(C(=O)O)C(=O)c3c(C)c2F)C4CC4,17136,CHEMBL583,=,104000.0,IC50,nM,K+ channel blocking activity in Chinese hamste...,Homo sapiens,F,9,HERG,CHEMBL240

The `describe()` method provides an statistical summary of the numerical columns.

In [53]:
df.describe()

           molregno  standard_value  confidence_score
count  8.989000e+03    8.989000e+03       8989.000000
mean   1.162010e+06    9.680188e+05          8.944599
std    6.612153e+05    2.558712e+07          0.228774
min    9.700000e+01    1.400000e-01          8.000000
25%    5.569920e+05    1.880000e+03          9.000000
50%    1.280901e+06    9.400000e+03          9.000000
75%    1.748621e+06    2.900000e+04          9.000000
max    2.196506e+06    1.000000e+09          9.000000

## Converting Datatypes
Note, Pandas thinks that the molregno column is an integer because numerical values are written. But this is just and ID of the molecule, so converting the column to a string would be a better choice for this case. Let's fix it.

In [54]:
df["molregno"] = df["molregno"].astype(str)
df.dtypes

canonical_smiles      object
molregno              object
mol_chembl_id         object
standard_relation     object
standard_value       float64
standard_type         object
standard_units        object
description           object
organism              object
assay_type            object
confidence_score       int64
pref_name             object
tgt_chembl_id         object
dtype: object

## Finding Duplicate molecules
We have to check how many unique molecules are there in the dataframe. Duplicate molecules don't serve any purpose. So, either we have to remove them or average out them.